gait_planner:
  ros__parameters:
    control_loop_frequency: 100.0  # Hz
    limb_prefixes: # must match (name & order) in commander_params.yaml
      - fr
      - fl
      - br
      - bl

    # Home point
    home_x: -0.012
    home_y: 0.02088
    home_z: -0.078
