controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_group_position_controller:
  ros__parameters:
    # Joint names must be listed in the same order produced by concatenating each limb prefix
    # with each joint suffix from locomotion_params.yaml.
    joints:
      - fr_haa_joint
      - fr_hfe_joint
      - fr_kfe_joint
      - fl_haa_joint
      - fl_hfe_joint
      - fl_kfe_joint
      - br_haa_joint
      - br_hfe_joint
      - br_kfe_joint
      - bl_haa_joint
      - bl_hfe_joint
      - bl_kfe_joint
